import type { ThemeMode } from '../../composables/useTheme'

export function applyThemeVars(t: ThemeMode) {
  const root = document.documentElement
  if (t === 'dark') {
    root.style.setProperty('--color-primary', '#6D5EF6')
    root.style.setProperty('--color-primary-hover-gradient-start', '#4E3FD4')
    root.style.setProperty('--color-primary-hover-gradient-end', '#4E3FD4')
    root.style.setProperty('--color-primary-hover', '#4E3FD4')
    root.style.setProperty('--color-primary-active', '#4536BD')
    root.style.setProperty('--color-primary-light', '#2F2A63')
    root.style.setProperty('--color-primary-disabled-gradient-start', 'color-mix(in srgb, var(--color-primary) 55%, var(--color-card-bg))')
    root.style.setProperty('--color-primary-disabled-bg', 'color-mix(in srgb, var(--color-primary) 55%, var(--color-card-bg))')
    root.style.setProperty('--color-primary-disabled-border', 'color-mix(in srgb, var(--color-primary) 48%, var(--color-card-bg))')
    root.style.setProperty('--color-primary-disabled-text', 'color-mix(in srgb, #FFFFFF 65%, var(--color-primary))')
    root.style.setProperty('--tnav-bg', '#0F0F17')
    root.style.setProperty('--tnav-overlay', 'linear-gradient(180deg, rgba(255, 255, 255, 0.045), rgba(255, 255, 255, 0))')
    root.style.setProperty('--tnav-border', 'rgba(26, 30, 48, 0.75)')
    root.style.setProperty('--tnav-shadow', '0 12px 26px rgba(0, 0, 0, 0.22)')
    root.style.setProperty('--tnav-text', '#fff')
    root.style.setProperty('--nav-item-color', '#bec2d4')
    root.style.setProperty('--nav-item-hover-color', '#ffffff')
    root.style.setProperty('--nav-item-hover-bg', 'rgba(255, 255, 255, 0.055)')
    root.style.setProperty('--nav-item-active-color', '#fff')
    root.style.setProperty('--nav-item-active-bg', 'rgba(109, 94, 246, 0.14)')
    root.style.setProperty('--nav-active-accent', '#F5A623')
    root.style.setProperty('--nav-active-line-shadow', '0 -2px 14px rgba(245, 166, 35, 0.35)')
    root.style.setProperty('--brand-color', '#6D5EF6')
    root.style.setProperty('--brand-glow', 'rgba(109, 94, 246, 0.56)')
    root.style.setProperty('--icon-btn-color', '#aeb2c5')
    root.style.setProperty('--icon-btn-hover-bg', 'rgba(255, 255, 255, 0.08)')
    root.style.setProperty('--icon-btn-hover-color', '#ffffff')
    root.style.setProperty('--tz-color', '#aeb2c5')
    root.style.setProperty('--tz-bg', 'rgba(255, 255, 255, 0.045)')
    root.style.setProperty('--tz-border', 'rgba(255, 255, 255, 0.08)')
    root.style.setProperty('--nav-user-trigger-color', 'rgba(255, 255, 255, 0.88)')
    root.style.setProperty('--nav-user-trigger-hover-color', '#fff')
    root.style.setProperty('--nav-user-trigger-hover-bg', 'rgba(255, 255, 255, 0.14)')
    root.style.setProperty('--nav-user-trigger-caret-color', 'rgba(255, 255, 255, 0.72)')
    root.style.setProperty('--nav-user-trigger-caret-hover-color', 'rgba(255, 255, 255, 0.95)')
    root.style.setProperty('--nav-notification-color', 'rgba(255, 255, 255, 0.8)')
    root.style.setProperty('--nav-notification-hover-color', '#fff')
    root.style.setProperty('--sidebar-bg', '#16161D')
    root.style.setProperty('--sidebar-border', '#2A2B35')
    root.style.setProperty('--sidebar-text', '#9A9CAE')
    root.style.setProperty('--sidebar-hover-bg', 'rgba(255, 255, 255, 0.04)')
    root.style.setProperty('--sidebar-hover-color', '#E2E2E2')
    root.style.setProperty('--sidebar-active-bg', 'linear-gradient(90deg, rgba(109, 94, 246, 0.22), rgba(109, 94, 246, 0.05))')
    root.style.setProperty('--sidebar-active-color', '#f8fbff')
    root.style.setProperty('--sidebar-active-line-bg', '#F5A623')
    root.style.setProperty('--sidebar-section', '#70727B')
    root.style.setProperty('--sidebar-subtext-color', '#9A9CAE')
    root.style.setProperty('--sidebar-shadow', 'none')
    root.style.setProperty('--content-bg', '#111116')
    root.style.setProperty('--page-bg', '#1A1A22')
    root.style.setProperty('--page-border', '#2A2B35')
    root.style.setProperty('--page-text', '#E2E2E2')
    root.style.setProperty('--page-text-secondary', '#9A9CAE')
    // Card, border and text semantic colors for dark mode
    root.style.setProperty('--color-card-bg', '#1C1D24')
    root.style.setProperty('--color-border', '#2A2B35')
    root.style.setProperty('--color-border-light', '#3A3B45')
    root.style.setProperty('--color-text-title', '#E2E2E2')
    root.style.setProperty('--color-text-primary', '#A0A0A8')
    root.style.setProperty('--color-text-secondary', '#787880')
    root.style.setProperty('--color-text-tertiary', '#5A5A65')
    root.style.setProperty('--color-text-placeholder', '#5A5A65')
    root.style.setProperty('--color-text-disabled', '#404048')
    root.style.setProperty('--color-grey-1', '#1C1D24')
    root.style.setProperty('--color-grey-2', '#252630')
    // Element Plus component dark mode overrides
    root.style.setProperty('--el-fill-color-blank', '#1C1D24')
    root.style.setProperty('--el-bg-color', '#141414')
    root.style.setProperty('--el-bg-color-overlay', '#1C1D24')
    root.style.setProperty('--el-popper-bg', '#1C1D24')
    root.style.setProperty('--el-popper-shadow-opacity', '0.35')
    root.style.setProperty('--hfl-popper-radius', '10px')
    root.style.setProperty('--el-popper-border-radius', '10px')
    root.style.setProperty('--el-text-color-primary', '#E2E2E2')
    root.style.setProperty('--el-text-color-regular', '#A0A0A8')
    root.style.setProperty('--el-text-color-secondary', '#787880')
    root.style.setProperty('--el-text-color-placeholder', '#5A5A65')
    root.style.setProperty('--el-text-color-disabled', '#404048')
    root.style.setProperty('--el-border-color', '#2A2B35')
    root.style.setProperty('--el-border-color-light', '#3A3B45')
    root.style.setProperty('--el-border-color-lighter', '#3A3B45')
    root.style.setProperty('--el-fill-color', '#252630')
    root.style.setProperty('--el-fill-color-light', '#1C1D24')
    root.style.setProperty('--el-fill-color-lighter', '#1C1D24')
    root.style.setProperty('--el-mask-color', '#00000080')
    root.style.setProperty('--el-overlay-color', '#000000b3')
    root.style.setProperty('--el-overlay-color-light', '#00000066')
    // Button hover/focus: use subtle primary tint instead of white
    root.style.setProperty('--el-button-hover-bg-color', 'rgba(109, 94, 246, 0.15)')
    root.style.setProperty('--el-button-hover-border-color', 'rgba(109, 94, 246, 0.4)')
    root.style.setProperty('--el-button-hover-text-color', '#A99BFF')
    root.style.setProperty('--el-color-primary-light-9', 'rgba(109, 94, 246, 0.12)')
    root.style.setProperty('--el-color-primary-light-7', 'rgba(109, 94, 246, 0.24)')
  } else if (t === 'light') {
    root.style.setProperty('--color-primary', '#6D5EF6')
    root.style.setProperty('--color-primary-hover-gradient-start', '#4E3FD4')
    root.style.setProperty('--color-primary-hover-gradient-end', '#4E3FD4')
    root.style.setProperty('--color-primary-hover', '#4E3FD4')
    root.style.setProperty('--color-primary-active', '#4536BD')
    root.style.setProperty('--color-primary-light', '#F2F0FE')
    root.style.setProperty('--color-primary-disabled-gradient-start', 'color-mix(in srgb, var(--color-primary) 80%, var(--color-card-bg))')
    root.style.setProperty('--color-primary-disabled-bg', 'color-mix(in srgb, var(--color-primary) 80%, var(--color-card-bg))')
    root.style.setProperty('--color-primary-disabled-border', 'color-mix(in srgb, var(--color-primary) 74%, var(--color-card-bg))')
    root.style.setProperty('--color-primary-disabled-text', 'color-mix(in srgb, #FFFFFF 70%, var(--color-primary))')
    root.style.setProperty('--tnav-bg', '#0F0F17')
    root.style.setProperty('--tnav-overlay', 'linear-gradient(180deg, rgba(255, 255, 255, 0.045), rgba(255, 255, 255, 0))')
    root.style.setProperty('--tnav-border', 'rgba(26, 30, 48, 0.75)')
    root.style.setProperty('--tnav-shadow', '0 12px 26px rgba(23, 27, 45, 0.18)')
    root.style.setProperty('--tnav-text', '#fff')
    root.style.setProperty('--nav-item-color', '#bec2d4')
    root.style.setProperty('--nav-item-hover-color', '#ffffff')
    root.style.setProperty('--nav-item-hover-bg', 'rgba(255, 255, 255, 0.055)')
    root.style.setProperty('--nav-item-active-color', '#fff')
    root.style.setProperty('--nav-item-active-bg', 'rgba(109, 94, 246, 0.14)')
    root.style.setProperty('--nav-active-accent', '#F5A623')
    root.style.setProperty('--nav-active-line-shadow', '0 -2px 14px rgba(245, 166, 35, 0.35)')
    root.style.setProperty('--brand-color', '#6D5EF6')
    root.style.setProperty('--brand-glow', 'rgba(109, 94, 246, 0.5)')
    root.style.setProperty('--icon-btn-color', '#aeb2c5')
    root.style.setProperty('--icon-btn-hover-bg', 'rgba(255, 255, 255, 0.08)')
    root.style.setProperty('--icon-btn-hover-color', '#ffffff')
    root.style.setProperty('--tz-color', '#aeb2c5')
    root.style.setProperty('--tz-bg', 'rgba(255, 255, 255, 0.045)')
    root.style.setProperty('--tz-border', 'rgba(255, 255, 255, 0.08)')
    root.style.setProperty('--nav-user-trigger-color', 'rgba(255, 255, 255, 0.88)')
    root.style.setProperty('--nav-notification-color', 'rgba(255, 255, 255, 0.8)')
    root.style.setProperty('--nav-notification-hover-color', '#fff')
    root.style.setProperty('--nav-user-trigger-color', 'rgba(255, 255, 255, 0.88)')
    root.style.setProperty('--nav-user-trigger-hover-color', '#fff')
    root.style.setProperty('--nav-user-trigger-hover-bg', 'rgba(255, 255, 255, 0.14)')
    root.style.setProperty('--nav-user-trigger-caret-color', 'rgba(255, 255, 255, 0.72)')
    root.style.setProperty('--nav-user-trigger-caret-hover-color', 'rgba(255, 255, 255, 0.95)')
    root.style.setProperty('--sidebar-bg', '#FCFCFD')
    root.style.setProperty('--sidebar-border', '#E9E9EF')
    root.style.setProperty('--sidebar-text', '#3A3A48')
    root.style.setProperty('--sidebar-hover-bg', 'rgba(109, 94, 246, 0.07)')
    root.style.setProperty('--sidebar-hover-color', '#1C1C26')
    root.style.setProperty('--sidebar-active-bg', 'linear-gradient(90deg, rgba(109, 94, 246, 0.9), rgba(109, 94, 246, 0.72))')
    root.style.setProperty('--sidebar-active-color', '#FFFFFF')
    root.style.setProperty('--sidebar-active-line-bg', '#F5A623')
    root.style.setProperty('--sidebar-section', '#9C9CAA')
    root.style.setProperty('--sidebar-subtext-color', '#3A3A48')
    root.style.setProperty('--sidebar-shadow', '8px 0 18px rgba(28, 28, 38, 0.05)')
    root.style.setProperty('--content-bg', '#F4F4F7')
    root.style.setProperty('--page-bg', '#ffffff')
    root.style.setProperty('--page-border', '#E9E9EF')
    root.style.setProperty('--page-text', '#1C1C26')
    root.style.setProperty('--page-text-secondary', '#70707E')
    // Semantic card, border and text colors for light mode
    root.style.setProperty('--color-card-bg', '#ffffff')
    root.style.setProperty('--color-border', '#E9E9EF')
    root.style.setProperty('--color-border-light', '#F2F2F6')
    root.style.setProperty('--color-text-title', '#1C1C26')
    root.style.setProperty('--color-text-primary', '#3A3A48')
    root.style.setProperty('--color-text-secondary', '#70707E')
    root.style.setProperty('--color-text-tertiary', '#9C9CAA')
    root.style.setProperty('--color-text-placeholder', '#9C9CAA')
    root.style.setProperty('--color-text-disabled', '#BFBFC8')
    root.style.setProperty('--color-grey-1', '#FAFAFA')
    root.style.setProperty('--color-grey-2', '#F5F5F7')
    root.style.setProperty('--color-grey-3', '#F0F0F4')
    // Element Plus light mode overrides
    root.style.setProperty('--el-fill-color-blank', '#ffffff')
    root.style.setProperty('--el-bg-color', '#ffffff')
    root.style.setProperty('--el-bg-color-page', '#F4F4F7')
    root.style.setProperty('--el-bg-color-overlay', '#ffffff')
    root.style.setProperty('--el-text-color-primary', '#1C1C26')
    root.style.setProperty('--el-text-color-regular', '#3A3A48')
    root.style.setProperty('--el-text-color-secondary', '#70707E')
    root.style.setProperty('--el-text-color-placeholder', '#9C9CAA')
    root.style.setProperty('--el-text-color-disabled', '#BFBFC8')
    root.style.setProperty('--el-border-color', '#E9E9EF')
    root.style.setProperty('--el-border-color-light', '#F2F2F6')
    root.style.setProperty('--el-border-color-lighter', '#F2F2F6')
    root.style.setProperty('--el-fill-color', '#F5F5F7')
    root.style.setProperty('--el-fill-color-light', '#F5F5F7')
    root.style.setProperty('--el-fill-color-lighter', '#FAFAFA')
    root.style.setProperty('--el-popper-bg', '#ffffff')
    root.style.setProperty('--el-popper-shadow-opacity', '0.08')
    root.style.setProperty('--hfl-popper-radius', '10px')
    root.style.setProperty('--el-popper-border-radius', '10px')
    root.style.setProperty('--el-mask-color', 'rgba(255, 255, 255, 0.8)')
    root.style.setProperty('--el-overlay-color', 'rgba(0, 0, 0, 0.5)')
    root.style.setProperty('--el-overlay-color-light', 'rgba(0, 0, 0, 0.2)')
  } else {
    // hybrid - reference visual style: dark navigation, light content
    root.style.setProperty('--color-primary', '#6D5EF6')
    root.style.setProperty('--color-primary-hover-gradient-start', '#4E3FD4')
    root.style.setProperty('--color-primary-hover-gradient-end', '#4E3FD4')
    root.style.setProperty('--color-primary-hover', '#4E3FD4')
    root.style.setProperty('--color-primary-active', '#4536BD')
    root.style.setProperty('--color-primary-light', '#F2F0FE')
    root.style.setProperty('--color-primary-disabled-gradient-start', 'color-mix(in srgb, var(--color-primary) 80%, var(--color-card-bg))')
    root.style.setProperty('--color-primary-disabled-bg', 'color-mix(in srgb, var(--color-primary) 80%, var(--color-card-bg))')
    root.style.setProperty('--color-primary-disabled-border', 'color-mix(in srgb, var(--color-primary) 74%, var(--color-card-bg))')
    root.style.setProperty('--color-primary-disabled-text', 'color-mix(in srgb, #FFFFFF 70%, var(--color-primary))')
    root.style.setProperty('--nav-active-accent', '#F5A623')
    root.style.setProperty('--tnav-bg', '#0F0F17')
    root.style.setProperty('--tnav-overlay', 'linear-gradient(180deg, rgba(255, 255, 255, 0.035), rgba(255, 255, 255, 0))')
    root.style.setProperty('--tnav-border', 'rgba(109, 94, 246, 0.24)')
    root.style.setProperty('--tnav-shadow', '0 1px 0 rgba(255, 255, 255, 0.04), 0 12px 28px rgba(9, 8, 15, 0.28)')
    root.style.setProperty('--tnav-text', '#f8fafc')
    root.style.setProperty('--nav-item-color', '#9ca3af')
    root.style.setProperty('--nav-item-hover-color', '#e5e7eb')
    root.style.setProperty('--nav-item-hover-bg', 'rgba(109, 94, 246, 0.08)')
    root.style.setProperty('--nav-item-active-color', '#ffffff')
    root.style.setProperty('--nav-item-active-bg', 'rgba(109, 94, 246, 0.1)')
    root.style.setProperty('--nav-item-active-overlay', 'none')
    root.style.setProperty('--nav-active-line-start', '#F5A623')
    root.style.setProperty('--nav-active-line-end', '#F5A623')
    root.style.setProperty('--nav-active-line-shadow', '0 -2px 18px rgba(245, 166, 35, 0.5)')
    root.style.setProperty('--brand-color', '#6D5EF6')
    root.style.setProperty('--brand-glow', 'rgba(109, 94, 246, 0.64)')
    root.style.setProperty('--icon-btn-color', '#a1a1aa')
    root.style.setProperty('--icon-btn-hover-bg', 'rgba(109, 94, 246, 0.12)')
    root.style.setProperty('--icon-btn-hover-color', '#ffffff')
    root.style.setProperty('--tz-color', '#cbd5e1')
    root.style.setProperty('--tz-bg', 'rgba(22, 163, 74, 0.12)')
    root.style.setProperty('--tz-border', 'rgba(34, 197, 94, 0.24)')
    root.style.setProperty('--nav-user-trigger-color', '#f8fafc')
    root.style.setProperty('--nav-user-trigger-hover-color', '#ffffff')
    root.style.setProperty('--nav-user-trigger-hover-bg', 'rgba(109, 94, 246, 0.12)')
    root.style.setProperty('--nav-user-trigger-caret-color', '#a1a1aa')
    root.style.setProperty('--nav-user-trigger-caret-hover-color', '#f8fafc')
    root.style.setProperty('--nav-notification-color', '#a1a1aa')
    root.style.setProperty('--nav-notification-hover-color', '#ffffff')
    root.style.setProperty('--sidebar-bg', '#0F0F17')
    root.style.setProperty('--sidebar-overlay', 'linear-gradient(180deg, rgba(255, 255, 255, 0.035), rgba(255, 255, 255, 0))')
    root.style.setProperty('--sidebar-border', 'rgba(109, 94, 246, 0.22)')
    root.style.setProperty('--sidebar-text', '#C6C6D2')
    root.style.setProperty('--sidebar-hover-bg', 'rgba(109, 94, 246, 0.12)')
    root.style.setProperty('--sidebar-hover-color', '#FFFFFF')
    root.style.setProperty('--sidebar-active-bg', 'linear-gradient(90deg, rgba(109, 94, 246, 0.28), rgba(109, 94, 246, 0.06))')
    root.style.setProperty('--sidebar-active-color', '#FFFFFF')
    root.style.setProperty('--sidebar-active-line-bg', '#F5A623')
    root.style.setProperty('--sidebar-section', '#76768A')
    root.style.setProperty('--sidebar-subtext-color', '#A8A8B8')
    root.style.setProperty('--sidebar-shadow', '8px 0 24px rgba(9, 8, 15, 0.18)')
    root.style.setProperty('--content-bg', '#F4F4F7')
    root.style.setProperty('--page-bg', '#ffffff')
    root.style.setProperty('--page-border', '#E9E9EF')
    root.style.setProperty('--page-text', '#1C1C26')
    root.style.setProperty('--page-text-secondary', '#70707E')
    // Semantic card, border and text colors for hybrid (light content)
    root.style.setProperty('--color-card-bg', '#ffffff')
    root.style.setProperty('--color-border', '#E9E9EF')
    root.style.setProperty('--color-border-light', '#F2F2F6')
    root.style.setProperty('--color-text-title', '#1C1C26')
    root.style.setProperty('--color-text-primary', '#3A3A48')
    root.style.setProperty('--color-text-secondary', '#70707E')
    root.style.setProperty('--color-text-tertiary', '#9C9CAA')
    root.style.setProperty('--color-text-placeholder', '#9C9CAA')
    root.style.setProperty('--color-text-disabled', '#BFBFC8')
    root.style.setProperty('--color-grey-1', '#FAFAFA')
    root.style.setProperty('--color-grey-2', '#F5F5F7')
    root.style.setProperty('--color-grey-3', '#F0F0F4')
    // Element Plus light mode overrides for content area
    root.style.setProperty('--el-fill-color-blank', '#ffffff')
    root.style.setProperty('--el-bg-color', '#ffffff')
    root.style.setProperty('--el-bg-color-page', '#F4F4F7')
    root.style.setProperty('--el-bg-color-overlay', '#ffffff')
    root.style.setProperty('--el-text-color-primary', '#1C1C26')
    root.style.setProperty('--el-text-color-regular', '#3A3A48')
    root.style.setProperty('--el-text-color-secondary', '#70707E')
    root.style.setProperty('--el-text-color-placeholder', '#9C9CAA')
    root.style.setProperty('--el-text-color-disabled', '#BFBFC8')
    root.style.setProperty('--el-border-color', '#E9E9EF')
    root.style.setProperty('--el-border-color-light', '#F2F2F6')
    root.style.setProperty('--el-border-color-lighter', '#F2F2F6')
    root.style.setProperty('--el-fill-color', '#F5F5F7')
    root.style.setProperty('--el-fill-color-light', '#FAFAFA')
    root.style.setProperty('--el-fill-color-lighter', '#FBFBFD')
    root.style.setProperty('--el-popper-bg', '#ffffff')
    root.style.setProperty('--el-popper-shadow-opacity', '0.08')
    root.style.setProperty('--hfl-popper-radius', '10px')
    root.style.setProperty('--el-popper-border-radius', '10px')
    root.style.setProperty('--el-mask-color', 'rgba(255, 255, 255, 0.8)')
    root.style.setProperty('--el-overlay-color', 'rgba(0, 0, 0, 0.5)')
    root.style.setProperty('--el-overlay-color-light', 'rgba(0, 0, 0, 0.2)')
  }
}
