"""Runtime defaults for node communication."""

import os

from project.settings.env import env_int, env_str

# Agent WSS heartbeat is every 30s (agent/internal/wire/types.go). TTLs must exceed
# that interval so ``effective_agent_node_status`` does not flicker offline between beats.
_AGENT_HEARTBEAT_SECONDS = 30
_AGENT_LOC_TTL_MARGIN = 3

AGENT_LOC_TTL_SECONDS = env_int(
    "NODE_AGENT_LOC_TTL_SECONDS",
    _AGENT_HEARTBEAT_SECONDS * _AGENT_LOC_TTL_MARGIN,
)
TASK_WATCHDOG_SECONDS = env_int("NODE_TASK_WATCHDOG_SECONDS", 60)
AUTOMATIC_PROBE_WATCHDOG_SECONDS = env_int(
    "NODE_AUTOMATIC_PROBE_WATCHDOG_SECONDS",
    210,
)
SNAPSHOT_DELETE_WATCHDOG_SECONDS = env_int(
    "NODE_SNAPSHOT_DELETE_WATCHDOG_SECONDS",
    3660,
)
TASK_COMMAND_ACK_TIMEOUT_SECONDS = env_int("NODE_TASK_COMMAND_ACK_TIMEOUT_SECONDS", 30)
TASK_COMMAND_ACK_MAX_RETRIES = env_int("NODE_TASK_COMMAND_ACK_MAX_RETRIES", 3)
TASK_COMMAND_ACK_MAX_AGE_SECONDS = env_int("NODE_TASK_COMMAND_ACK_MAX_AGE_SECONDS", 600)
TASK_COMMAND_ACK_RECONCILE_INTERVAL_SECONDS = env_int(
    "NODE_TASK_COMMAND_ACK_RECONCILE_INTERVAL_SECONDS", 15
)
TASK_ROUTE_RECONNECT_GRACE_SECONDS = env_int(
    "NODE_TASK_ROUTE_RECONNECT_GRACE_SECONDS", 30
)
TASK_SYNC_WAIT_SECONDS = env_int("NODE_TASK_SYNC_WAIT_SECONDS", 15)
TASK_STREAM_MAX_MESSAGES = max(
    1,
    env_int("NODE_TASK_STREAM_MAX_MESSAGES", 64),
)
TASK_STREAM_TTL_GRACE_SECONDS = max(
    60,
    env_int("NODE_TASK_STREAM_TTL_GRACE_SECONDS", 60),
)
TASK_CANCEL_GRACE_SECONDS = env_int("NODE_TASK_CANCEL_GRACE_SECONDS", 300)
WATCHDOG_SWEEP_INTERVAL_SECONDS = env_int("NODE_WATCHDOG_SWEEP_INTERVAL_SECONDS", 30)
STALE_NODE_RECONCILE_INTERVAL_SECONDS = env_int(
    "NODE_STALE_NODE_RECONCILE_INTERVAL_SECONDS",
    60,
)
NODE_RECONNECT_GRACE_SECONDS = env_int("NODE_RECONNECT_GRACE_SECONDS", 90)
# After reconnect grace expires (offline), wait this long before failing active tasks.
OFFLINE_TASK_FAIL_SECONDS = env_int("NODE_OFFLINE_TASK_FAIL_SECONDS", 90)
WS_RECOVERY_HOLD_SECONDS = env_int(
    "NODE_WS_RECOVERY_HOLD_SECONDS",
    NODE_RECONNECT_GRACE_SECONDS + OFFLINE_TASK_FAIL_SECONDS,
)
LIFECYCLE_CORRELATION_TYPE = "node.lifecycle"
LIFECYCLE_MAX_CONCURRENT = env_int("NODE_LIFECYCLE_MAX_CONCURRENT", 5)
LIFECYCLE_MAX_CONCURRENT_HARD = env_int("NODE_LIFECYCLE_MAX_CONCURRENT_HARD", 10)
# Detached upgrade/remove: agent stops service and WS drops; use long watchdog + verify window.
LIFECYCLE_DETACHED_TIMEOUT_SECONDS = env_int(
    "NODE_LIFECYCLE_DETACHED_TIMEOUT_SECONDS", 600
)
UNINSTALL_COMPLETION_MAX_AGE_SECONDS = env_int(
    "NODE_UNINSTALL_COMPLETION_MAX_AGE_SECONDS",
    LIFECYCLE_DETACHED_TIMEOUT_SECONDS + 300,
)
UPGRADE_VERIFY_TIMEOUT_SECONDS = env_int(
    "NODE_UPGRADE_VERIFY_TIMEOUT_SECONDS",
    LIFECYCLE_DETACHED_TIMEOUT_SECONDS,
)
# After reconnect + version match, WS must stay routable this long before SUCCESS.
UPGRADE_STABLE_SECONDS = env_int("NODE_UPGRADE_STABLE_SECONDS", 8)
# Soft verify-phase reference (logging/docs); no hard failure at this boundary.
UPGRADE_VERIFY_MAX_SECONDS = env_int("NODE_UPGRADE_VERIFY_MAX_SECONDS", 15)
UPGRADE_MIN_FREE_BYTES = env_int("NODE_UPGRADE_MIN_FREE_BYTES", 512 * 1024 * 1024)
UPGRADE_MAX_DISK_USED_PCT = env_int("NODE_UPGRADE_MAX_DISK_USED_PCT", 90)
REMOVE_PURGE_GRACE_SECONDS = env_int("NODE_REMOVE_PURGE_GRACE_SECONDS", 30)
# After detached uninstall, WS drop must persist this long before CP marks SUCCESS + purge.
REMOVE_FINALIZE_SECONDS = env_int("NODE_REMOVE_FINALIZE_SECONDS", 30)
REMOVE_DISCONNECT_FINALIZE_SECONDS = env_int(
    "NODE_REMOVE_DISCONNECT_FINALIZE_SECONDS",
    REMOVE_FINALIZE_SECONDS,
)
WS_INSTANCE_ALIVE_TTL_SECONDS = env_int(
    "NODE_WS_INSTANCE_ALIVE_TTL_SECONDS",
    _AGENT_HEARTBEAT_SECONDS * _AGENT_LOC_TTL_MARGIN,
)
WS_INSTANCE_ID = env_str("NODE_WS_INSTANCE_ID", "") or os.getenv("HOSTNAME", "ws-local")
WS_INSTANCE_KEEPALIVE_INTERVAL_SECONDS = env_int(
    "NODE_WS_INSTANCE_KEEPALIVE_INTERVAL_SECONDS",
    _AGENT_HEARTBEAT_SECONDS,
)
LIFECYCLE_ADVANCE_INTERVAL_SECONDS = env_int(
    "NODE_LIFECYCLE_ADVANCE_INTERVAL_SECONDS", 2
)
# WebSocket connect/disconnect callbacks are edge-triggered.  Coalesce bursts
# from a flapping Agent into one lifecycle wake-up; the periodic sweep remains
# the durable fallback for events that arrive while Redis is unavailable.
LIFECYCLE_EVENT_COALESCE_SECONDS = env_int(
    "NODE_LIFECYCLE_EVENT_COALESCE_SECONDS",
    _AGENT_HEARTBEAT_SECONDS,
)
HEARTBEAT_INVENTORY_MIN_INTERVAL_SECONDS = env_int(
    "NODE_HEARTBEAT_INVENTORY_MIN_INTERVAL_SECONDS",
    300,
)
UPLINK_INGEST_INTERVAL_SECONDS = env_int("NODE_UPLINK_INGEST_INTERVAL_SECONDS", 1)
UPLINK_INGEST_BATCH_SIZE = env_int("NODE_UPLINK_INGEST_BATCH_SIZE", 200)

# Periodic queue entries are disposable wake-ups. They must expire before a
# stopped worker can accumulate hours of obsolete maintenance work.
UPLINK_INGEST_EXPIRE_SECONDS = max(2, UPLINK_INGEST_INTERVAL_SECONDS * 3)
LIFECYCLE_ADVANCE_EXPIRE_SECONDS = max(5, LIFECYCLE_ADVANCE_INTERVAL_SECONDS * 3)
UPLINK_INGEST_LOCK_SECONDS = max(10, UPLINK_INGEST_EXPIRE_SECONDS * 2)
LIFECYCLE_ADVANCE_LOCK_SECONDS = max(60, LIFECYCLE_ADVANCE_EXPIRE_SECONDS * 10)
UPLINK_INGEST_DRAIN_SECONDS = 2
UPLINK_PENDING_RECLAIM_IDLE_MS = 5_000
UPLINK_DLQ_MIN_DELIVERIES = 100
UPLINK_DLQ_MIN_AGE_SECONDS = 3_600
TASK_UPLINK_PROJECTION_GRACE_SECONDS = 30
TASK_RESULT_UPLINK_PROJECTION_GRACE_SECONDS = 300

# Enrollment install-link lifetime.
ENROLLMENT_TOKEN_TTL_SECONDS = env_int(
    "ENROLLMENT_TOKEN_TTL_SECONDS",
    24 * 3600,
)
