/** Registry code → i18n key under errors.codes.* */
export const ERROR_CODE_I18N_KEYS: Record<string, string> = {
  'NETWORK.UNAVAILABLE': 'errors.codes.networkUnavailable',
  'NETWORK.TIMEOUT': 'errors.codes.networkTimeout',
  'CLIENT.OFFLINE': 'errors.codes.clientOffline',
  'CLIENT.ABORTED': 'errors.codes.clientAborted',
  'UNKNOWN.ERROR': 'errors.codes.unknown',
  'VALIDATION.FAILED': 'errors.codes.validationFailed',
  'AUTH.FORBIDDEN': 'errors.codes.authForbidden',
  'RESOURCE.NOT_FOUND': 'errors.codes.resourceNotFound',
  'RESOURCE.CONFLICT': 'errors.codes.resourceConflict',
  'STORAGE.REPOSITORY_ALREADY_EXISTS': 'errors.codes.storageRepositoryAlreadyExists',
  'STORAGE.REPOSITORY_OPERATION_NOT_CANCELLABLE': 'errors.codes.storageRepositoryOperationNotCancellable',
  'STORAGE.REPOSITORY_OPERATION_NOT_ACTIVE': 'errors.codes.storageRepositoryOperationNotActive',
  'STORAGE.S3_CREDENTIALS_INVALID': 'errors.codes.storageS3CredentialsInvalid',
  'STORAGE.S3_PERMISSION_DENIED': 'errors.codes.storageS3PermissionDenied',
  'STORAGE.S3_BUCKET_ACCESS_DENIED': 'errors.codes.storageS3BucketAccessDenied',
  'STORAGE.S3_BUCKET_NOT_FOUND': 'errors.codes.storageS3BucketNotFound',
  'STORAGE.S3_BUCKET_NAME_INVALID': 'errors.codes.storageS3BucketNameInvalid',
  'STORAGE.S3_BUCKET_NAME_UNAVAILABLE': 'errors.codes.storageS3BucketNameUnavailable',
  'STORAGE.S3_CONFIGURATION_INVALID': 'errors.codes.storageS3ConfigurationInvalid',
  'STORAGE.S3_NETWORK_UNAVAILABLE': 'errors.codes.storageS3NetworkUnavailable',
  'STORAGE.S3_TIMEOUT': 'errors.codes.storageS3Timeout',
  'STORAGE.S3_TLS_FAILED': 'errors.codes.storageS3TlsFailed',
  'STORAGE.S3_VALIDATION_FAILED': 'errors.codes.storageS3ValidationFailed',
  'INSIGHT.DATA_GATEWAY_UNAVAILABLE': 'errors.codes.insightDataGatewayUnavailable',
  'INSIGHT.REPOSITORY_READER_UNAVAILABLE': 'errors.codes.insightRepositoryReaderUnavailable',
  'INSIGHT.REPOSITORY_READER_UPGRADE_REQUIRED': 'errors.codes.insightRepositoryReaderUpgradeRequired',
  'INSIGHT.REPOSITORY_UNAVAILABLE': 'errors.codes.insightRepositoryUnavailable',
  'INSIGHT.SNAPSHOT_UNAVAILABLE': 'errors.codes.insightSnapshotUnavailable',
  'INSIGHT.SNAPSHOT_PATH_NOT_FOUND': 'errors.codes.insightSnapshotPathNotFound',
  'INSIGHT.SNAPSHOT_BROWSE_TIMEOUT': 'errors.codes.insightSnapshotBrowseTimeout',
  'INSIGHT.UNSUPPORTED_CONTENT_TYPE': 'errors.codes.insightUnsupportedContentType',
  'INSIGHT.SNAPSHOT_BROWSE_FAILED': 'errors.codes.insightSnapshotBrowseFailed',
  'INSIGHT.CHAT_MODEL_NOT_VISION_CAPABLE': 'errors.codes.insightChatModelNotVisionCapable',
  'INSIGHT.CHAT_ASSISTANT_CREATE_UNKNOWN': 'errors.codes.insightChatAssistantCreateUnknown',
  'INSIGHT.CHAT_PREPARATION_FAILED': 'errors.codes.insightChatPreparationFailed',
  'INSIGHT.GATEWAY_CHAT_QUEUE_FULL': 'errors.codes.insightGatewayChatQueueFull',
  'SERVER.INTERNAL_ERROR': 'errors.codes.serverInternal',
  'AGENT.TIMEOUT': 'errors.codes.agentTimeout',
  'AGENT.UNREACHABLE': 'errors.codes.agentUnreachable',
  'AGENT.PATH_PERMISSION_DENIED': 'errors.codes.agentPathPermissionDenied',
  'AGENT.PATH_PROTECTED': 'errors.codes.agentPathProtected',
  'AGENT.EXPLORER_LIST_FAILED': 'errors.codes.agentExplorerListFailed',
  'AGENT.PATH_VALIDATE_FAILED': 'errors.codes.agentPathValidateFailed',
  'AGENT.NAS_MOUNT_FAILED': 'errors.codes.agentNasMountFailed',
  'SMB_CHARSET_UNAVAILABLE': 'errors.codes.smbCharsetUnavailable',
  'AGENT.TASK_FAILED': 'errors.codes.agentTaskFailed',
  'BACKUP.QUOTA_EXCEEDED': 'errors.codes.backupQuotaExceeded',
  'BACKUP.REPOSITORY_QUOTA_EXCEEDED': 'errors.codes.backupRepositoryQuotaExceeded',
  'SUBSCRIPTION.QUOTA_EXCEEDED': 'errors.codes.subscriptionQuotaExceeded',
  'SUBSCRIPTION.QUOTA_USAGE_UNAVAILABLE': 'errors.codes.subscriptionQuotaUsageUnavailable',
  'BACKUP.ALREADY_RUNNING': 'errors.codes.backupAlreadyRunning',
  'RESTORE.ALREADY_RUNNING': 'errors.codes.restoreAlreadyRunning',
}

export const ERROR_CODE_FALLBACK_EN: Record<string, string> = {
  'NETWORK.UNAVAILABLE': 'Unable to connect. Check your network and try again.',
  'NETWORK.TIMEOUT': 'Request timed out. Please try again later.',
  'CLIENT.OFFLINE': 'You are offline. Check your network connection.',
  'UNKNOWN.ERROR': 'Something went wrong. Please try again.',
  'VALIDATION.FAILED': 'Please check the form and try again.',
  'AUTH.FORBIDDEN': "You don't have permission to perform this action.",
  'RESOURCE.NOT_FOUND': "This resource doesn't exist or was removed.",
  'STORAGE.REPOSITORY_ALREADY_EXISTS': 'A Kopia repository already exists at the selected location. Import is not supported in this version. Choose a different storage location.',
  'STORAGE.REPOSITORY_OPERATION_NOT_CANCELLABLE': 'Only controller-managed S3 maintenance tasks can be cancelled.',
  'STORAGE.REPOSITORY_OPERATION_NOT_ACTIVE': 'This maintenance task has already finished. Refresh to see its latest status.',
  'STORAGE.S3_CREDENTIALS_INVALID': 'Object storage credentials were rejected. Check the Access Key and Secret Key, then try again.',
  'STORAGE.S3_PERMISSION_DENIED': 'The credentials cannot list object storage buckets. Grant the required IAM permission, then try again.',
  'STORAGE.S3_BUCKET_ACCESS_DENIED': 'The credentials cannot read and write the selected bucket. Grant the required bucket permissions, then try again.',
  'STORAGE.S3_BUCKET_NOT_FOUND': 'The bucket was not found. Check the bucket name, endpoint, and Region, then try again.',
  'STORAGE.S3_BUCKET_NAME_INVALID': 'The bucket name is not valid for this object storage provider. Check the naming rules and try again.',
  'STORAGE.S3_BUCKET_NAME_UNAVAILABLE': 'The bucket name is already in use. If the bucket belongs to this account, select Existing Bucket; otherwise choose another name.',
  'STORAGE.S3_CONFIGURATION_INVALID': 'The object storage connection settings are invalid. Check the endpoint, Region, URL style, and TLS setting, then try again.',
  'STORAGE.S3_NETWORK_UNAVAILABLE': 'The object storage endpoint could not be reached. Check the endpoint and network connectivity, then try again.',
  'STORAGE.S3_TIMEOUT': 'The object storage request timed out. Check the endpoint and network connectivity, then try again.',
  'STORAGE.S3_TLS_FAILED': 'The TLS certificate could not be verified. Check the endpoint certificate and TLS setting, then try again.',
  'STORAGE.S3_VALIDATION_FAILED': 'Object storage validation failed. Check the connection settings and IAM permissions, then try again.',
  'INSIGHT.DATA_GATEWAY_UNAVAILABLE': 'The selected Data Gateway is unavailable. Bring its Agent and LensNode online, then try again.',
  'INSIGHT.REPOSITORY_READER_UNAVAILABLE': 'The Repository Reader is unavailable. Check its Proxy binding and Agent status, then try again.',
  'INSIGHT.REPOSITORY_READER_UPGRADE_REQUIRED': 'Upgrade the Repository Reader Agent before browsing or using this backup in Chat.',
  'INSIGHT.REPOSITORY_UNAVAILABLE': 'The snapshot repository is unavailable. Check the repository and try again.',
  'INSIGHT.SNAPSHOT_UNAVAILABLE': 'The selected snapshot is no longer available. Choose another snapshot.',
  'INSIGHT.SNAPSHOT_PATH_NOT_FOUND': 'The selected file or folder is no longer available in this snapshot.',
  'INSIGHT.SNAPSHOT_BROWSE_TIMEOUT': 'Snapshot browsing timed out. Check the Reader and try again.',
  'INSIGHT.UNSUPPORTED_CONTENT_TYPE': 'Symbolic links, sockets, pipes, and device files cannot be used in Chat.',
  'INSIGHT.SNAPSHOT_BROWSE_FAILED': 'Unable to browse the selected snapshot. Try again.',
  'INSIGHT.CHAT_MODEL_NOT_VISION_CAPABLE': 'The configured AI model is not compatible with this Chat. Ask an administrator to check the multimodal model, then try again.',
  'INSIGHT.CHAT_ASSISTANT_CREATE_UNKNOWN': 'The AI service did not confirm Chat creation. Temporary resources are being cleaned up before you retry.',
  'INSIGHT.CHAT_PREPARATION_FAILED': 'Chat preparation failed. Try again or contact your administrator.',
  'INSIGHT.GATEWAY_CHAT_QUEUE_FULL': 'This Data Gateway has reached its Chat waiting limit. Try again later or use another Data Gateway.',
  'SERVER.INTERNAL_ERROR': 'Service is temporarily unavailable. Please try again later.',
  'AGENT.TIMEOUT': 'Agent timed out. Confirm the node is online and try again.',
  'AGENT.UNREACHABLE': 'Agent is unreachable. Confirm the node is online.',
  'AGENT.PATH_PERMISSION_DENIED': 'The Agent does not have permission to access this path. Choose a readable path or use Host files · continuous when broader host access is required.',
  'AGENT.PATH_PROTECTED': 'This directory is managed by the HyperFileLens Agent and cannot be selected as a backup source.',
  'AGENT.EXPLORER_LIST_FAILED': 'Failed to browse directory. Confirm the node is online and try again.',
  'AGENT.PATH_VALIDATE_FAILED': 'Path validation failed. Check the path and try again.',
  'AGENT.NAS_MOUNT_FAILED': 'NAS mount operation failed. Check connection settings.',
  'SMB_CHARSET_UNAVAILABLE': 'SMB UTF-8 filename support is unavailable on the Proxy Host. Install the matching kernel extra-modules package, then remount the share.',
  'AGENT.TASK_FAILED': 'Agent task failed. Please try again.',
  'BACKUP.QUOTA_EXCEEDED': 'Backup quota exceeded. Upgrade your subscription and try again.',
  'BACKUP.REPOSITORY_QUOTA_EXCEEDED':
    'This backup repository has reached its configured Storage Quota. Free repository space or increase Storage Quota before retrying.',
  'SUBSCRIPTION.QUOTA_EXCEEDED':
    'Organization quota is full. Contact your platform administrator to raise limits.',
  'SUBSCRIPTION.QUOTA_USAGE_UNAVAILABLE':
    'Capacity information is temporarily unavailable. Try again shortly.',
  'BACKUP.ALREADY_RUNNING': 'A backup is starting or running for this source. Stop it or wait for it to finish before continuing.',
  'RESTORE.ALREADY_RUNNING': 'A restore task is already running for this source.',
}

/** Canonical quota_type → English meter label (fallback when i18n is unavailable). */
export const QUOTA_TYPE_METER_FALLBACK_EN: Record<string, string> = {
  max_users: 'Users',
  users: 'Users',
  max_organizations: 'Organizations',
  max_storage_gb: 'Storage',
  storage: 'Storage',
  max_gateways: 'Private Data Gateways',
  gateways: 'Private Data Gateways',
  max_public_gateways: 'Public Data Gateways',
  max_alert_policies: 'Alert Rules',
  alert_policies: 'Alert Rules',
  max_public_gateway_capacity_bytes: 'Public Gateway Capacity',
  public_gateway_capacity: 'Public Gateway Capacity',
  'gateway.public_capacity_bytes': 'Public Gateway workspace',
  max_nodes: 'Nodes',
  max_source_hosts: 'Source Hosts',
  hosts: 'Source Hosts',
  agents: 'Source Hosts',
  nodes: 'Source Hosts',
  max_proxies: 'Source Agents',
  proxies: 'Source Agents',
  max_source_nas: 'Source NAS',
  source_nas: 'Source NAS',
  max_object_storage: 'Object Storage',
  object_storage: 'Object Storage',
  max_target_nas: 'Target NAS',
  target_nas: 'Target NAS',
  max_standalone_disk: 'Local Disk',
  standalone_disk: 'Local Disk',
  max_protected_sources: 'Protected Sources',
  protected_sources: 'Protected Sources',
  ai_tokens: 'AI Tokens (lifetime)',
  ai_requests: 'AI Tokens (lifetime)',
  ai: 'AI Tokens (lifetime)',
  ai_insights: 'AI Tokens (lifetime)',
  ai_insights_quota: 'AI Tokens (lifetime)',
  gateway_select_max_files: 'Gateway Select file count',
  gateway_select_max_bytes: 'Gateway Select size',
}

/** Caller aliases → canonical quota / pool keys used in APIs and licenseQuota.* */
const QUOTA_TYPE_ALIASES: Record<string, string> = {
  users: 'max_users',
  storage: 'max_storage_gb',
  gateways: 'max_gateways',
  public_gateway_capacity: 'max_public_gateway_capacity_bytes',
  'gateway.public_capacity_bytes': 'max_public_gateway_capacity_bytes',
  hosts: 'max_source_hosts',
  agents: 'max_source_hosts',
  nodes: 'max_source_hosts',
  proxies: 'max_proxies',
  source_nas: 'max_source_nas',
  object_storage: 'max_object_storage',
  target_nas: 'max_target_nas',
  standalone_disk: 'max_standalone_disk',
  protected_sources: 'max_protected_sources',
  ai: 'ai_tokens',
  ai_tokens: 'ai_tokens',
  ai_requests: 'ai_tokens',
  ai_insights: 'ai_tokens',
  ai_insights_quota: 'ai_tokens',
}

export function canonicalizeQuotaType(quotaType: unknown): string {
  const key = String(quotaType || '').trim().toLowerCase()
  return QUOTA_TYPE_ALIASES[key] || key
}

export function quotaTypeMeterLabel(quotaType: unknown): string {
  const key = canonicalizeQuotaType(quotaType)
  return QUOTA_TYPE_METER_FALLBACK_EN[key] || QUOTA_TYPE_METER_FALLBACK_EN[String(quotaType || '').trim().toLowerCase()] || ''
}

const BROWSER_NETWORK_PATTERNS = [
  'failed to fetch',
  'networkerror when attempting to fetch resource',
  'load failed',
  'network request failed',
]

export function isBrowserNetworkMessage(message: string): boolean {
  const m = message.trim().toLowerCase()
  return BROWSER_NETWORK_PATTERNS.some((p) => m.includes(p))
}

export function isRegistryCode(code: string): boolean {
  return Boolean(code && ERROR_CODE_I18N_KEYS[code])
}
