# Generated by Django 5.1.4 on 2026-10-09 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0020_repository_health_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorymaintenancestate',
            name='full_day_group',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repositorymaintenancestate',
            name='full_slot_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repositorymaintenancestate',
            name='next_reconcile_due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='repositorymaintenancestate',
            name='schedule_timezone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='repositorytask',
            name='operation_type',
            field=models.CharField(choices=[('maintenance.quick', 'Quick maintenance'), ('maintenance.full', 'Full maintenance'), ('snapshot.reconcile', 'Orphan snapshot reconciliation'), ('cleanup.target', 'Delete subrepository'), ('cleanup.repository', 'Delete repository'), ('check', 'Check'), ('credential.rotate', 'Update Credentials'), ('create.repository', 'Create repository'), ('repair.bind', 'Bind proxy'), ('repair.remount', 'Remount repository')], db_index=True, max_length=64),
        ),
        migrations.CreateModel(
            name='RepositoryOrphanSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_id', models.CharField(max_length=128)),
                ('source', models.JSONField(default=dict)),
                ('operation_id', models.CharField(blank=True, default='', max_length=200)),
                ('first_seen_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('status', models.CharField(db_index=True, default='candidate', max_length=30)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('delete_node_task_id', models.UUIDField(blank=True, null=True)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storage.repositoryexecutiontarget')),
            ],
            options={
                'db_table': 'storage_orphan_snapshot',
                'indexes': [models.Index(fields=['target', 'status'], name='storage_orphan_target_status')],
                'constraints': [models.UniqueConstraint(fields=('target', 'snapshot_id'), name='storage_orphan_target_snapshot')],
            },
        ),
    ]
