# Generated by Django 5.1.4 on 2026-09-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_config', '0004_remove_obsolete_backup_concurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalconfig',
            name='value',
            field=models.JSONField(blank=True),
        ),
    ]
