// @vitest-environment jsdom

import { mount } from '@vue/test-utils'
import { describe, expect, it } from 'vitest'
import { createI18n } from 'vue-i18n'
import { en } from '../../locales/en'
import CopilotMarkdown from './CopilotMarkdown.vue'

const i18n = createI18n({ legacy: false, locale: 'en', messages: { en } })

function mountMarkdown(content: string) {
  return mount(CopilotMarkdown, {
    global: { plugins: [i18n] },
    props: { content },
  })
}

describe('CopilotMarkdown', () => {
  it('renders safe links without allowing executable protocols', () => {
    const wrapper = mountMarkdown([
          '[Documentation](https://example.com/docs)',
          '[Unsafe](javascript:alert(1))',
          '<img src=x onerror=alert(1)>',
        ].join('\n\n'))

    const links = wrapper.findAll('a')
    expect(links).toHaveLength(1)
    expect(links[0].attributes()).toEqual(expect.objectContaining({
      href: 'https://example.com/docs',
      rel: 'noopener noreferrer',
      target: '_blank',
    }))
    expect(wrapper.html()).toContain('Unsafe')
    expect(wrapper.html()).not.toContain('javascript:')
    expect(wrapper.find('img').attributes('src')).toBe('x')
    expect(wrapper.html()).not.toContain('onerror')
  })

  it('preserves allowlisted raw HTML while sanitizing executable markup', () => {
    const wrapper = mountMarkdown('<span class="source-note">SourceLens note</span><script>alert(1)</script>')

    expect(wrapper.get('.source-note').text()).toBe('SourceLens note')
    expect(wrapper.find('script').exists()).toBe(false)
  })

  it('renders SourceLens answer structures without changing their content', () => {
    const wrapper = mountMarkdown([
          '## Generated files',
          '',
          'The file `/test.py` is ready.',
          '',
          '```python',
          'print("Hello, world!")',
          '```',
          '',
          '| Name | Version |',
          '| --- | --- |',
          '| Python | 3.12 |',
          '',
          '> Generated by SourceLens',
        ].join('\n'))

    expect(wrapper.get('h2').text()).toBe('Generated files')
    expect(wrapper.get('.copilot-md-code-language').text()).toBe('python')
    expect(wrapper.get('.copilot-md-code-copy').attributes('aria-label')).toBe('Copy')
    expect(wrapper.get('pre code').text()).toBe('print("Hello, world!")')
    expect(wrapper.get('.copilot-md-table-wrap table').text()).toContain('Python')
    expect(wrapper.get('blockquote').text()).toBe('Generated by SourceLens')
  })

  it('keeps a streaming code fence readable before SourceLens closes it', () => {
    const wrapper = mountMarkdown('```javascript\nconst ready = true')

    expect(wrapper.get('.copilot-md-code-language').text()).toBe('javascript')
    expect(wrapper.get('pre code').text()).toBe('const ready = true')
  })

  it('preserves SourceLens soft line breaks as rendered lines', () => {
    const wrapper = mountMarkdown('First line\nSecond line')

    expect(wrapper.get('p').html()).toContain('First line<br>Second line')
    expect(wrapper.text()).not.toContain('<br>')
  })

  it('supports GFM images, task lists, and strikethrough safely', () => {
    const wrapper = mountMarkdown([
          '![Diagram](https://example.com/diagram.png)',
          '',
          '- [x] Indexed',
          '- [ ] Pending',
          '',
          '~~obsolete~~',
        ].join('\n'))

    expect(wrapper.get('img').attributes()).toEqual(expect.objectContaining({
      src: 'https://example.com/diagram.png',
      alt: 'Diagram',
      loading: 'lazy',
    }))
    expect(wrapper.findAll('input[type="checkbox"]')).toHaveLength(2)
    expect(wrapper.get('del').text()).toBe('obsolete')
  })

  it('renders SourceLens mindmap fences as a safe visual outline', () => {
    const wrapper = mountMarkdown('```mindmap\n# Workspace\n- Source\n  - File\n```')
    expect(wrapper.get('svg.copilot-md-mindmap').attributes('role')).toBe('tree')
    expect(wrapper.findAll('[data-mindmap-action]')).toHaveLength(5)
    expect(wrapper.text()).toContain('Source')
    expect(wrapper.text()).toContain('File')
  })

  it('supports SourceLens-style mindmap controls without leaving the answer', async () => {
    const wrapper = mountMarkdown('```mindmap\n# Workspace\n- Source\n  - File\n```')
    const root = wrapper.get('[data-mindmap-root]')
    await root.find('[data-mindmap-action="zoom-in"]').trigger('click')
    expect(root.get('svg').attributes('data-zoom')).toBe('1.15')
    expect(root.get('svg').attributes('style')).toContain('width:')
    await root.find('[data-mindmap-action="code"]').trigger('click')
    expect(root.classes()).toContain('copilot-md-mindmap--code')
    await root.find('[data-mindmap-action="code"]').trigger('click')
    await root.get('[data-mindmap-path="0.1"]').trigger('click')
    expect(root.get('[data-mindmap-path="0.1"]').attributes('aria-expanded')).toBe('false')
  })
})
