// @vitest-environment jsdom

import { mount } from '@vue/test-utils'
import { describe, expect, it } from 'vitest'
import CopilotMarkdown from './CopilotMarkdown.vue'

describe('CopilotMarkdown', () => {
  it('renders safe links without allowing executable protocols', () => {
    const wrapper = mount(CopilotMarkdown, {
      props: {
        content: [
          '[Documentation](https://example.com/docs)',
          '[Unsafe](javascript:alert(1))',
          '<img src=x onerror=alert(1)>',
        ].join('\n\n'),
      },
    })

    const links = wrapper.findAll('a')
    expect(links).toHaveLength(1)
    expect(links[0].attributes()).toEqual(expect.objectContaining({
      href: 'https://example.com/docs',
      rel: 'noopener noreferrer',
      target: '_blank',
    }))
    expect(wrapper.html()).toContain('Unsafe')
    expect(wrapper.html()).not.toContain('javascript:')
    expect(wrapper.html()).toContain('&lt;img src=x onerror=alert(1)&gt;')
  })

  it('renders SourceLens answer structures without changing their content', () => {
    const wrapper = mount(CopilotMarkdown, {
      props: {
        content: [
          '## Generated files',
          '',
          'The file `/test.py` is ready.',
          '',
          '```python',
          'print("Hello, world!")',
          '```',
          '',
          '| Name | Version |',
          '| --- | --- |',
          '| Python | 3.12 |',
          '',
          '> Generated by SourceLens',
        ].join('\n'),
      },
    })

    expect(wrapper.get('h2').text()).toBe('Generated files')
    expect(wrapper.get('.copilot-md-code-language').text()).toBe('python')
    expect(wrapper.get('pre code').text()).toBe('print("Hello, world!")')
    expect(wrapper.get('.copilot-md-table-wrap table').text()).toContain('Python')
    expect(wrapper.get('blockquote').text()).toBe('Generated by SourceLens')
  })

  it('keeps a streaming code fence readable before SourceLens closes it', () => {
    const wrapper = mount(CopilotMarkdown, {
      props: {
        content: '```javascript\nconst ready = true',
      },
    })

    expect(wrapper.get('.copilot-md-code-language').text()).toBe('javascript')
    expect(wrapper.get('pre code').text()).toBe('const ready = true')
  })

  it('preserves SourceLens soft line breaks as rendered lines', () => {
    const wrapper = mount(CopilotMarkdown, {
      props: {
        content: 'First line\nSecond line',
      },
    })

    expect(wrapper.get('p').html()).toContain('First line<br>Second line')
    expect(wrapper.text()).not.toContain('<br>')
  })
})
