# Generated by Django 5.2 on 2026-08-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("task", "0010_node_lifecycle_and_warning_step")]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("waiting", "Waiting"),
                    ("running", "Running"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("timeout", "Timeout"),
                ],
                db_index=True,
                default="pending",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="TaskDependency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reference_type", models.CharField(choices=[("task", "Task"), ("node_task", "Node task"), ("external", "External condition")], default="external", max_length=24)),
                ("reference_id", models.CharField(blank=True, default="", max_length=128)),
                ("reference_task_type", models.CharField(blank=True, default="", max_length=64)),
                ("code", models.CharField(db_index=True, max_length=64)),
                ("detail", models.TextField()),
                ("auto_resumable", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("blocking_task", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="blocked_tasks", to="task.task")),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="dependencies", to="task.task")),
            ],
            options={"db_table": "task_dependency", "ordering": ["created_at", "id"]},
        ),
        migrations.AddIndex(
            model_name="taskdependency",
            index=models.Index(fields=["task", "is_active"], name="task_dep_task_active_idx"),
        ),
        migrations.AddIndex(
            model_name="taskdependency",
            index=models.Index(fields=["reference_type", "reference_id", "is_active"], name="task_dep_ref_active_idx"),
        ),
    ]
