"""Protection backup orchestration defaults (override via Django settings)."""

from project.settings.env import env_bool, env_int, env_str

PROTECTION_BACKUP_CORRELATION_TYPE = "protection.backup"
PROTECTION_BACKUP_POLICY_PREPARE_CORRELATION_TYPE = "protection.backup.policy_prepare"
PROTECTION_BACKUP_NODE_TASK_KINDS = frozenset(
    {"backup.run", "backup.snapshot.create"}
)

PROTECTION_BACKUP_PREPARED_SNAPSHOT_ENABLED = env_bool(
    "PROTECTION_BACKUP_PREPARED_SNAPSHOT_ENABLED",
    default=True,
)
PROTECTION_BACKUP_POLICY_PREPARE_MAX_RETRIES = env_int(
    "PROTECTION_BACKUP_POLICY_PREPARE_MAX_RETRIES",
    3,
)
PROTECTION_BACKUP_POLICY_PREPARE_RETRY_DELAYS = (1, 4, 16)

PROTECTION_BACKUP_RECONCILE_INTERVAL_SECONDS = env_int(
    "PROTECTION_BACKUP_RECONCILE_INTERVAL_SECONDS",
    30,
)
PROTECTION_BACKUP_QUEUE_STALE_SECONDS = env_int(
    "PROTECTION_BACKUP_QUEUE_STALE_SECONDS", 900
)
PROTECTION_BACKUP_QUEUE_RECOVERY_GRACE_SECONDS = env_int(
    "PROTECTION_BACKUP_QUEUE_RECOVERY_GRACE_SECONDS", 120
)
PROTECTION_BACKUP_DIRECTORY_CONCURRENCY = env_str(
    "PROTECTION_BACKUP_DIRECTORY_CONCURRENCY",
    "parallel",
)

PROTECTION_BACKUP_SUBSTANTIVE_STALL_WARN_SECONDS = env_int(
    "PROTECTION_BACKUP_SUBSTANTIVE_STALL_WARN_SECONDS",
    1800,
)
# Agent-side Kopia watchdog is the primary stall terminator. This longer control
# plane deadline is a final safety net for old Agents or failed local watchdogs.
PROTECTION_BACKUP_SUBSTANTIVE_STALL_FAIL_SECONDS = env_int(
    "PROTECTION_BACKUP_SUBSTANTIVE_STALL_FAIL_SECONDS",
    7200,
)
PROTECTION_BACKUP_CANCEL_GRACE_SECONDS = env_int(
    "PROTECTION_BACKUP_CANCEL_GRACE_SECONDS",
    300,
)
PROTECTION_BACKUP_LATE_SUCCESS_ADOPT_SECONDS = env_int(
    "PROTECTION_BACKUP_LATE_SUCCESS_ADOPT_SECONDS",
    259200,
)
PROTECTION_BACKUP_REATTACH_GRACE_SECONDS = env_int(
    "PROTECTION_BACKUP_REATTACH_GRACE_SECONDS",
    900,
)
PROTECTION_BACKUP_CAPABILITY_SYNC_GRACE_SECONDS = env_int(
    "PROTECTION_BACKUP_CAPABILITY_SYNC_GRACE_SECONDS",
    120,
)
PROTECTION_BACKUP_DISABLE_SHORT_WATCHDOG = env_bool(
    "PROTECTION_BACKUP_DISABLE_SHORT_WATCHDOG",
    default=True,
)
PROTECTION_BACKUP_AUTO_RETRY_ENABLED = env_bool(
    "PROTECTION_BACKUP_AUTO_RETRY_ENABLED",
    default=False,
)
PROTECTION_BACKUP_AUTO_RETRY_MAX = env_int("PROTECTION_BACKUP_AUTO_RETRY_MAX", 3)
PROTECTION_BACKUP_DISPATCH_PENDING_SECONDS = env_int(
    "PROTECTION_BACKUP_DISPATCH_PENDING_SECONDS",
    120,
)

PROTECTION_BACKUP_NODE_TASK_WATCHDOG_SECONDS = env_int(
    "PROTECTION_BACKUP_NODE_TASK_WATCHDOG_SECONDS",
    7200,
)
PROTECTION_BACKUP_ACTIVITY_LEASE_SECONDS = env_int(
    "PROTECTION_BACKUP_ACTIVITY_LEASE_SECONDS",
    300,
)
PROTECTION_PROXY_REPOSITORY_SERVER_ENABLED = env_bool(
    "PROTECTION_PROXY_REPOSITORY_SERVER_ENABLED",
    default=True,
)

LATE_SUCCESS_ADOPT_ERROR_CODES = frozenset(
    {
        "WATCHDOG_STALL",
        "RESULT_ACK_TIMEOUT",
        "KOPIA_PROGRESS_STALL",
        "AGENT_TIMEOUT",
        "AGENT_OFFLINE",
        "AGENT_RESTARTED",
    }
)

AUTO_RETRY_ERROR_CODES = frozenset(
    {
        "KOPIA_PROCESS_DIED",
        "KOPIA_SIGNAL_KILLED",
        "KOPIA_PROGRESS_STALL",
        "AGENT_RESTARTED",
        "AGENT_BACKUP_FAILED",
    }
)
