"""IAM policy defaults (overridable via GlobalConfig)."""

CONFIG_KEY_REGISTRATION_TOKEN_EXPIRY_HOURS = "iam.registration.token_expiry_hours"
CONFIG_KEY_REGISTRATION_TOKEN_EXPIRY_MINUTES = "iam.registration.token_expiry_minutes"
CONFIG_KEY_PASSWORD_RESET_TIMEOUT = "iam.password_reset.timeout_seconds"
CONFIG_KEY_PASSWORD_RESET_TIMEOUT_MINUTES = "iam.password_reset.timeout_minutes"
CONFIG_KEY_REGISTRATION_CODE_MINUTES = "iam.registration.verification_code_minutes"
CONFIG_KEY_PASSWORD_RESET_CODE_MINUTES = "iam.password_reset.verification_code_minutes"
CONFIG_KEY_LOGIN_CODE_MINUTES = "iam.login.verification_code_minutes"

DEFAULT_REGISTRATION_TOKEN_EXPIRY_HOURS = 24
DEFAULT_REGISTRATION_TOKEN_EXPIRY_MINUTES = DEFAULT_REGISTRATION_TOKEN_EXPIRY_HOURS * 60
DEFAULT_PASSWORD_RESET_TIMEOUT_MINUTES = 60
DEFAULT_PASSWORD_RESET_TIMEOUT_SECONDS = DEFAULT_PASSWORD_RESET_TIMEOUT_MINUTES * 60
DEFAULT_REGISTRATION_VERIFICATION_CODE_MINUTES = 15
DEFAULT_PASSWORD_RESET_VERIFICATION_CODE_MINUTES = 10
DEFAULT_LOGIN_VERIFICATION_CODE_MINUTES = 10
